// Auto-generated built-in site catalog. No Cookie / account secrets here.
// User overrides live in config/sites.yaml and are merged on top.

export const BUILTIN_SITES = {
  "feng-com": {
    "enabled": true,
    "driver": "feng",
    "schedule": "auto",
    "note": "威锋论坛",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://www.feng.com/forum/",
    "signin_mode": "api",
    "category": "forum",
    "kind": "signin"
  },
  "nodeseek": {
    "enabled": true,
    "driver": "nodeseek",
    "schedule": "auto",
    "note": "NodeSeek 每日签到",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://www.nodeseek.com",
    "impersonate": "chrome142",
    "signin_mode": "playwright",
    "playwright_wait_ms": 5000,
    "proxy": "auto",
    "category": "forum"
  },
  "v2ex": {
    "enabled": true,
    "driver": "v2ex",
    "schedule": "auto",
    "note": "V2EX 每日签到",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://www.v2ex.com",
    "signin_mode": "playwright",
    "playwright_wait_ms": 2500,
    "proxy": "auto"
  },
  "naixi": {
    "enabled": true,
    "driver": "naixi",
    "schedule": "auto",
    "note": "奶昔论坛每日签到",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://forum.naixi.net",
    "signin_mode": "playwright",
    "playwright_wait_ms": 2500,
    "proxy": "auto"
  },
  "pojie52": {
    "enabled": true,
    "driver": "pojie52",
    "schedule": "auto",
    "note": "吾爱破解每日签到",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://www.52pojie.cn",
    "signin_mode": "playwright",
    "playwright_wait_ms": 2500,
    "proxy": "auto",
    "category": "forum",
    "daily_reward_points": 2
  },
  "nodeloc": {
    "enabled": true,
    "driver": "nodeloc",
    "schedule": "auto",
    "note": "NodeLoc 每日签到",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://www.nodeloc.com",
    "signin_mode": "playwright",
    "playwright_wait_ms": 2500,
    "proxy": "auto",
    "category": "forum",
    "kind": "signin"
  },
  "pceva": {
    "enabled": true,
    "driver": "pceva",
    "schedule": "auto",
    "note": "PCEVA 每日签到",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://www.pceva.com.cn",
    "signin_mode": "playwright",
    "playwright_wait_ms": 2500,
    "proxy": "auto",
    "category": "forum"
  },
  "chiphell-com": {
    "enabled": true,
    "driver": "chiphell",
    "schedule": "auto",
    "note": "Chiphell",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "http://www.chiphell.com/forum.php",
    "category": "forum",
    "kind": "visit",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "right": {
    "enabled": true,
    "driver": "right",
    "schedule": "auto",
    "note": "恩山无线论坛每日签到",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://www.right.com.cn/forum",
    "category": "forum",
    "kind": "signin",
    "proxy": "auto",
    "signin_mode": "playwright",
    "cookie_required_names": ["*_saltkey", "*_auth"]
  },
  "pcbeta": {
    "enabled": true,
    "driver": "pcbeta",
    "schedule": "auto",
    "note": "PCBeta",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://i.pcbeta.com",
    "signin_mode": "api",
    "category": "forum",
    "kind": "signin",
    "proxy": "auto",
    "cookie_required_names": ["*_saltkey", "*_auth"]
  },
  "audiences-me": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "Audiences",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://audiences.me/torrents.php",
    "category": "pt",
    "kind": "visit",
    "login_keyword": "Audiences",
    "verification_type": "Cloudflare Turnstile",
    "verification_auto": false,
    "signin_blocked_by_verification": false,
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "pt-btschool-club": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "BTSCHOOL",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://pt.btschool.club/torrents.php",
    "category": "pt",
    "kind": "visit",
    "login_keyword": "BTSCHOOL",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "carpt-net": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "CarPT",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://carpt.net/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "CarPT",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "pt-0ff-cc": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "FARMM",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://pt.0ff.cc/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "0ff",
    "verification_type": "简单滑块认证",
    "verification_auto": true,
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "hhanclub-net": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "HHanClub",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://hhanclub.net/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "HHanClub",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "hddolby-com": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "HDDolby",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://www.hddolby.com/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "HDDolby",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "hdfans-org": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "HDFans",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://hdfans.org/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "HDFans",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "hdhome-org": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "HDHome",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://hdhome.org/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "HDHome",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "hdsky-me": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "HDSky",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://hdsky.me/",
    "category": "pt",
    "kind": "visit",
    "enforced_kind": "visit",
    "login_keyword": "HDSky",
    "proxy": "auto",
    "signin_mode": "visit"
  },
  "open-cd": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "OpenCD",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://open.cd/",
    "category": "pt",
    "kind": "visit",
    "login_keyword": "OpenCD",
    "proxy": "auto",
    "signin_mode": "visit"
  },
  "ourbits-club": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "OurBits",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://ourbits.club/",
    "category": "pt",
    "kind": "visit",
    "enforced_kind": "visit",
    "login_keyword": "OurBits",
    "verification_type": "Cloudflare Turnstile",
    "verification_auto": false,
    "signin_blocked_by_verification": true,
    "verification_note": "OurBits 签到页需要 Cloudflare Turnstile，自动通过不稳定；已改为保活访问，不再触发签到入口。",
    "proxy": "auto",
    "signin_mode": "visit"
  },
  "piggo-me": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "Piggo",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://piggo.me/",
    "category": "pt",
    "kind": "visit",
    "login_keyword": "Piggo",
    "verification_type": "SafeLine 雷池 WAF",
    "verification_auto": false,
    "signin_blocked_by_verification": true,
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "pttime-org": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "PTTime",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://www.pttime.org/",
    "category": "pt",
    "kind": "visit",
    "login_keyword": "PTTime",
    "proxy": "auto",
    "signin_mode": "playwright"
  },
  "pterclub-net": {
    "enabled": true,
    "driver": "nexusphp",
    "schedule": "auto",
    "note": "PterClub",
    "notify": true,
    "retry": 2,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://pterclub.net/",
    "category": "pt",
    "kind": "signin",
    "login_keyword": "PterClub",
    "proxy": "auto",
    "signin_mode": "playwright",
    "cookie_required_names": ["c_secure_pass"]
  },
  "kafan": {
    "enabled": true,
    "driver": "kafan",
    "schedule": "auto",
    "note": "卡饭论坛",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://bbs.kafan.cn",
    "signin_mode": "playwright",
    "playwright_wait_ms": 1800,
    "proxy": "auto",
    "category": "forum",
    "kind": "signin"
  },
  "qianmoju": {
    "enabled": true,
    "driver": "qianmoju",
    "schedule": "auto",
    "note": "阡陌居每日签到",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://www.1000qm.vip",
    "signin_mode": "playwright",
    "playwright_wait_ms": 2500,
    "proxy": "on",
    "category": "forum",
    "kind": "signin"
  },
  "baidu-tieba": {
    "enabled": true,
    "driver": "tieba",
    "schedule": "auto",
    "note": "百度贴吧",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 60000,
    "base_url": "https://tieba.baidu.com",
    "signin_mode": "api",
    "proxy": "auto",
    "category": "forum",
    "kind": "signin"
  }
  ,
  "mteam": {
    "enabled": true,
    "driver": "mteam",
    "schedule": "auto",
    "note": "M-Team",
    "notify": true,
    "retry": 1,
    "retry_delay_ms": 10000,
    "timeout": 30000,
    "base_url": "https://kp.m-team.cc",
    "api_base_url": "https://api.m-team.cc/api",
    "signin_mode": "api",
    "proxy": "auto",
    "category": "pt",
    "kind": "visit"
  }
};

export default BUILTIN_SITES;
